<?php
//Almacenar en campos inputs escondidos los parámetros de entrada
$c_nombre=$_GET["nombre"];
$c_oposicion=$_GET["oposicion"];
$c_tema=$_GET["tema"];
$c_dificultad=$_GET["dificultad"];
$c_numeracion=$_GET["numeracion"];
$c_apartado=$_GET["apartado"];
$c_ciclos=$_GET["ciclos"];
$c_leyes=$_GET["leyes"];
$c_modulos=$_GET["modulos"];
$c_conceptoCita=$_GET["conceptoCita"];
$c_autorCita=$_GET["autorCita"];
$c_anyoCita=$_GET["anyoCita"];
$c_cita=$_GET["cita"];
$c_numeracionCita=$_GET["numeracionCita"];
$c_apartadoCita=$_GET["apartadoCita"];
$c_herramienta=$_GET["herramienta"];
$c_descripcionHerramienta=$_GET["descripcionHerramienta"];
$c_ensenyanza=$_GET["ensenyanza"];
$c_ciclosContexto=$_GET["ciclosContexto"];
$c_modulosContexto=$_GET["modulosContexto"];
$c_conceptoContextoEscolar=$_GET["conceptoContextoEscolar"];
$c_aplicacionContextoEscolar=$_GET["aplicacionContextoEscolar"];
$c_metodo=$_GET["metodo"];
$c_campo=$_GET["campo"];
$c_profesional=$_GET["profesional"];
$c_conceptoContextoLaboral=$_GET["conceptoContextoLaboral"];
$c_aplicacionContextoLaboral=$_GET["aplicacionContextoLaboral"];
$c_beneficio=$_GET["beneficio"];
$c_autorLibro=$_GET["autorLibro"];
$c_anyoLibro=$_GET["anyoLibro"];
$c_tituloLibro=$_GET["tituloLibro"];
$c_editorial=$_GET["editorial"];
$c_nombreWeb=$_GET["nombreWeb"];
$c_url=$_GET["url"];
print "<input type='hidden' value='$c_nombre' id='nombre'>";
print "<input type='hidden' value='$c_oposicion' id='oposicion'>";
print "<input type='hidden' value='$c_tema' id='tema'>";
print "<input type='hidden' value='$c_dificultad' id='dificultad'>";
print "<input type='hidden' value='$c_numeracion' id='numeracion'>";
print "<input type='hidden' value='$c_apartado' id='apartado'>";
print "<input type='hidden' value='$c_ciclos' id='ciclos'>";
print "<input type='hidden' value='$c_leyes' id='leyes'>";
print "<input type='hidden' value='$c_modulos' id='modulos'>";
print "<input type='hidden' value='$c_conceptoCita' id='conceptoCita'>";
print "<input type='hidden' value='$c_autorCita' id='autorCita'>";
print "<input type='hidden' value='$c_anyoCita' id='anyoCita'>";
print "<input type='hidden' value='$c_cita' id='cita'>";
print "<input type='hidden' value='$c_numeracionCita' id='numeracionCita'>";
print "<input type='hidden' value='$c_apartadoCita' id='apartadoCita'>";
print "<input type='hidden' value='$c_herramienta' id='herramienta'>";
print "<input type='hidden' value='$c_descripcionHerramienta' id='descripcionHerramienta'>";
print "<input type='hidden' value='$c_ensenyanza' id='ensenyanza'>";
print "<input type='hidden' value='$c_ciclosContexto' id='ciclosContexto'>";
print "<input type='hidden' value='$c_modulosContexto' id='modulosContexto'>";
print "<input type='hidden' value='$c_conceptoContextoEscolar' id='conceptoContextoEscolar'>";
print "<input type='hidden' value='$c_aplicacionContextoEscolar' id='aplicacionContextoEscolar'>";
print "<input type='hidden' value='$c_metodo' id='metodo'>";
print "<input type='hidden' value='$c_campo' id='campo'>";
print "<input type='hidden' value='$c_profesional' id='profesional'>";
print "<input type='hidden' value='$c_conceptoContextoLaboral' id='conceptoContextoLaboral'>";
print "<input type='hidden' value='$c_aplicacionContextoLaboral' id='aplicacionContextoLaboral'>";
print "<input type='hidden' value='$c_beneficio' id='beneficio'>";
print "<input type='hidden' value='$c_autorLibro' id='autorLibro'>";
print "<input type='hidden' value='$c_anyoLibro' id='anyoLibro'>";
print "<input type='hidden' value='$c_tituloLibro' id='tituloLibro'>";
print "<input type='hidden' value='$c_editorial' id='editorial'>";
print "<input type='hidden' value='$c_nombreWeb' id='nombreWeb'>";
print "<input type='hidden' value='$c_url' id='url'>";
?>